import "@/styles/globals.css";
import store from "../redux/store/store";
import { Provider } from "react-redux";
import Head from "next/head";
import Layout from "@/components/Layout/Layout";

export default function App({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Layout>
        <Head>
          <title>Netflix clone</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
         
        </Head>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  );
}
