import Head from "next/head";
import HomeScreen from "@/components/HomeScreen/HomeScreen";
import axios from "@/helpers/axios";
import requests from "@/helpers/Request";
import LoginScreen from "@/components/Login/LoginScreen";

export default function Home({ initialMovie }) {
  const user = null;
  return (
    <div style={{ backgroundColor: "#111" }}>
      <Head>
        <title>Netflix clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user ? <LoginScreen /> : <HomeScreen initialMovie={initialMovie} />}
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await axios(requests.fetchNetflixOriginals);
  const randomMovie =
    data.results[Math.floor(Math.random() * data.results.length - 1)];

  return {
    props: {
      initialMovie: randomMovie,
    },
  };
}
